OUTPUT = backtracking-poda

CXX = g++

CXXFLAGS = -Wall -Wextra -std=c++11

SOURCES = backtracking-poda.cpp

all: $(OUTPUT)

$(OUTPUT): $(SOURCES)
    $(CXX) $(CXXFLAGS) -o $(OUTPUT) $(SOURCES)

clean:
    rm -f $(OUTPUT)